name: CI
on:
  push:
    tags: [ '*' ]

jobs:
  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/matrix.json) | sed 's/ //g' )
          echo "matrix=$TASKS" >> $GITHUB_OUTPUT

  build:
    needs: matrix
    name: Build
    runs-on: windows-2019
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.cfg.python-version }}
          architecture: ${{ matrix.cfg.python-arch }}

      - name: Check Python install
        run: |
          which python
          python --version
          python -c "import struct; print(struct.calcsize('P') * 8)"
          which pip
          pip --version

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip setuptools wheel

      - name: Build
        run: |
          python setup.py bdist_wheel

      - name: Prepare for deployment
        run: |
          dir dist
          $ver = (findstr /R [0-9] VERSION)
          echo $ver
          echo "VER=$ver" >> $env:GITHUB_ENV
          $wheelname = python .github\helpers\get_wheel_name.py $ver
          echo $wheelname
          echo "WHEELNAME=$wheelname" >> $env:GITHUB_ENV

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WHEELNAME }}
          path: |
            dist/${{ env.WHEELNAME }}

      - name: Install
        run: |
          dir
          pip install dist/${{ env.WHEELNAME }}
          python -c "import zipextimporter"

      - name: Test
        run: |
          python test.py prepare
          python test.py test

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Prepare for release
        run: |
          python .github/helpers/gen_hash_body.py artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          bodyFile: "body.md"
          artifacts: "sha256.sum,artifacts/*/*.whl"
